export const GET_WEATHER_DATA_REQUEST = "GET_WEATHER_DATA_REQUEST";
export const GET_WEATHER_DATA_PENDING = "GET_WEATHER_DATA_PENDING";
export const GET_WEATHER_DATA_FAILED = "GET_WEATHER_DATA_FAILED";
export const GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS";
